<a href="https://colab.research.google.com/github/Mgobeaalcoba/Full_Pandas/blob/main/concat_append.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
pd.__version__

'1.1.5'

In [2]:
pd.options.display.float_format='{:.2f}'.format # Fijo 2 decimales max en pandas

In [3]:
np.set_printoptions(precision=2) # Fijo 2 decimales max en numpy

In [4]:
np.random.rand() # Sin parametros genera numeros aleatorios entre 0 y 1

0.05581457699754133

In [8]:
x1 = np.random.rand(2,5)*100 # Le paso por parametro que me genere aleatorios para 2 filas y 5 columnas
x1

array([[56.04, 79.55, 75.95, 94.7 , 92.08],
       [98.63, 38.72,  3.34, 92.85,  3.33]])

In [10]:
x2 = np.random.rand(2,5)*-100
x2

array([[-22.91, -74.42, -55.62, -93.11, -96.9 ],
       [-53.01,  -7.48, -58.75, -50.32, -76.11]])

In [11]:
#Puedo concatenar las dos matrices en numpy con np.concatenate([x1,x2])
np.concatenate([x1,x2])

array([[ 56.04,  79.55,  75.95,  94.7 ,  92.08],
       [ 98.63,  38.72,   3.34,  92.85,   3.33],
       [-22.91, -74.42, -55.62, -93.11, -96.9 ],
       [-53.01,  -7.48, -58.75, -50.32, -76.11]])

In [12]:
np.concatenate([x1,x2]).shape # Se han concatenado las filas por defecto

(4, 5)

In [13]:
np.concatenate([x1,x2],axis=1) # Asi concateno desde las columnas

array([[ 56.04,  79.55,  75.95,  94.7 ,  92.08, -22.91, -74.42, -55.62,
        -93.11, -96.9 ],
       [ 98.63,  38.72,   3.34,  92.85,   3.33, -53.01,  -7.48, -58.75,
        -50.32, -76.11]])

In [14]:
np.concatenate([x1,x2],axis=1).shape

(2, 10)

In [19]:
# Hagamos lo mismo con pandas
s1 = pd.Series(x1[0],index=["a","b","c","d","e"]) # Creo con una serie con la primer fila de x1
s1

a   56.04
b   79.55
c   75.95
d   94.70
e   92.08
dtype: float64

In [20]:
s2 = pd.Series(x2[0],index=["c","d","e","f","g"])
s2

c   -22.91
d   -74.42
e   -55.62
f   -93.11
g   -96.90
dtype: float64

In [24]:
pd.concat([s1,s2]) # Concateno las seríes en una sola columna

a    56.04
b    79.55
c    75.95
d    94.70
e    92.08
c   -22.91
d   -74.42
e   -55.62
f   -93.11
g   -96.90
dtype: float64

In [26]:
pd.concat([s1,s2],axis=1) # Concateno las seríes en dos culumnas. Una por cada serie
# Se concatenan respetando los indices que había definido. 

0      1
a 56.04    nan
b 79.55    nan
c 75.95 -22.91
d 94.70 -74.42
e 92.08 -55.62
f   nan -93.11
g   nan -96.90

In [29]:
# Con s1.reset_index puedo volver a usar los indices originales de mi serie
s1.reset_index()

index     0
0     a 56.04
1     b 79.55
2     c 75.95
3     d 94.70
4     e 92.08

In [30]:
# Si quiero que mi viejo indice directamente desaparezca entonces hago:
s1.reset_index(drop=True)

0   56.04
1   79.55
2   75.95
3   94.70
4   92.08
dtype: float64

In [31]:
s1

a   56.04
b   79.55
c   75.95
d   94.70
e   92.08
dtype: float64

In [34]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)],axis=1)

0      1
0 56.04 -22.91
1 79.55 -74.42
2 75.95 -55.62
3 94.70 -93.11
4 92.08 -96.90

In [35]:
# Vamos ahora a concatenar dataframes
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns=["a","b"])
df1

a    b
0 9.79 6.27
1 9.83 4.87
2 0.83 3.33

In [38]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns=["a","b"],index=[2,3,4])
df2

a     b
2 -0.99 -0.15
3 -0.11 -0.94
4 -0.37 -0.75

In [41]:
pd.concat([df1,df2])

a     b
0  9.79  6.27
1  9.83  4.87
2  0.83  3.33
2 -0.99 -0.15
3 -0.11 -0.94
4 -0.37 -0.75

In [42]:
pd.concat([df1,df2],axis=1)

a    b     a     b
0 9.79 6.27   nan   nan
1 9.83 4.87   nan   nan
2 0.83 3.33 -0.99 -0.15
3  nan  nan -0.11 -0.94
4  nan  nan -0.37 -0.75

In [43]:
# Puedo traer solo que se comparte entre mis dos dataframes
pd.concat([df1,df2],axis=1,join="inner")

a    b     a     b
2 0.83 3.33 -0.99 -0.15

In [49]:
# Unirlos previo reseteo de sus indices
pd.concat([df1.reset_index(drop=True),df2.reset_index(drop=True)],axis=1)

a    b     a     b
0 9.79 6.27 -0.99 -0.15
1 9.83 4.87 -0.11 -0.94
2 0.83 3.33 -0.37 -0.75

In [51]:
# Hay una forma mucho mas simple para unir dos dataframes
df1.append(df2).append(df2)

a     b
0  9.79  6.27
1  9.83  4.87
2  0.83  3.33
2 -0.99 -0.15
3 -0.11 -0.94
4 -0.37 -0.75
2 -0.99 -0.15
3 -0.11 -0.94
4 -0.37 -0.75

In [53]:
# Para usar append desde las columnas debo usar la traspuesta de nuestro dataframe
df1

a    b
0 9.79 6.27
1 9.83 4.87
2 0.83 3.33

In [56]:
df1.T.append(df2.T)

0    1     2     3     4
a 9.79 9.83  0.83   nan   nan
b 6.27 4.87  3.33   nan   nan
a  nan  nan -0.99 -0.11 -0.37
b  nan  nan -0.15 -0.94 -0.75

In [57]:
# Si quiero verlos en el mismo sentido que antes entonces saco la traspuesta nuevamente de mi append
df1.T.append(df2.T).T

a    b     a     b
0 9.79 6.27   nan   nan
1 9.83 4.87   nan   nan
2 0.83 3.33 -0.99 -0.15
3  nan  nan -0.11 -0.94
4  nan  nan -0.37 -0.75