<a href="https://colab.research.google.com/github/Mgobeaalcoba/Full_Pandas/blob/main/primeros_pasos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
my_array = np.array([[1,2,3,4,5,10],[10,1,2,3,4,5]])
my_array

array([[ 1,  2,  3,  4,  5, 10],
       [10,  1,  2,  3,  4,  5]])

In [ ]:
my_array + 10

array([[11, 12, 13, 14, 15, 20],
       [20, 11, 12, 13, 14, 15]])

In [ ]:
my_array.shape

(2, 6)

In [ ]:
my_array[0]

array([ 1,  2,  3,  4,  5, 10])

In [ ]:
my_array[0][0]

1

In [ ]:
sr = pd.Series([10,9,8,7,6]) # Las series a diferencia de los arrays son indexados
sr

0    10
1     9
2     8
3     7
4     6
dtype: int64

In [ ]:
sr.values 

array([10,  9,  8,  7,  6])

In [ ]:
sr.index # Muestra la dimensionalidad de mi serie

RangeIndex(start=0, stop=5, step=1)

In [ ]:
sr.shape

(5,)

In [ ]:
sr[3] # Me muestra solo el elemento solicitado. 

7

In [ ]:
sr[[0,4,2]] # Me muestra lso elementos guardados en mi lista en el orden escrito

0    10
4     6
2     8
dtype: int64

In [ ]:
sr = pd.Series([10,9,8,7,6],index=["a","b","c","d","e"]) # Así defino el indice que deseo
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [ ]:
sr["b":"e"] #Uso rebanadas con los indices para ver solo una parte

b    9
c    8
d    7
e    6
dtype: int64

Las series de Pandas funcionan muy parecido a los diccionarios de Python

In [ ]:
dict_data = {"CO":100,"MX":200,"AR":300}
dict_data

{'AR': 300, 'CO': 100, 'MX': 200}

In [ ]:
dict_data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [ ]:
dict_data.values()

dict_values([100, 200, 300])

In [ ]:
dict_data["MX"]

200

Un archivo json es muy parecido con un diccionario

podemos crear una serie sobre la base de un diccionario

In [ ]:
pd.Series(dict_data)

CO    100
MX    200
AR    300
dtype: int64

In [ ]:
pd.Series(dict_data,index=["CO","MX","PE"]) # Me arroja una serie con CO y MX del dict pero sin AR y PE con valor Nulo

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
# ¿Que es NaN? 
np.nan

nan

In [ ]:
np.nan+10

nan

In [ ]:
sr = pd.Series(dict_data,index=["CO","MX","PE"]) 
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [ ]:
sr.isnull() # Me marca en que parte de mi serie tengo valores nulos

CO    False
MX    False
PE     True
dtype: bool

In [ ]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool